### ISSUE TITLE
Verify the tekton signature in MicroShift at container deploy

### ISSUE THREAD

**Issue by jimcadden** [AICoE/summit-2021-octo-keynote#16]
For a signed container image MicroShift should pull the signature manifest from sigstore and validate the integrity of the container before it is deployed

**Comment by goern** [comment]
@lukehinds @harshad16 how do we do this? if tekton is creating a deployment one openshift, do we need some admission controller to have cosign verify the signature of the container image?

**Comment by jimcadden** [comment]
> @lukehinds @harshad16 how do we do this? if tekton is creating a deployment one openshift, do we need some admission controller to have cosign verify the signature of the container image?

@goern a [k8s admission controller](https://kubernetes.io/blog/2019/03/21/a-guide-to-kubernetes-admission-controllers/), installed and configured on microshift, can be used to verifying the container image. This is something we'll have to create. 

Next question, where is the key used to validate the signature stored / pulled from?

**Comment by goern** [comment]
/assign @harshad16 

@jimcadden we use argocd with kustomize, so its a ksops secret somewhere in an ops repo, see https://github.com/thoth-station/thoth-application/blob/master/core/overlays/rick-test/secrets.enc.yaml as an example...

**Comment by jimcadden** [comment]
https://github.com/operate-first/continuous-delivery/pull/22

**Comment by jimcadden** [comment]
https://github.com/operate-first/apps/pull/1427

**Comment by jimcadden** [comment]
https://github.com/operate-first/apps/pull/1404

**Comment by harshad16** [comment]
> Next question, where is the key used to validate the signature stored / pulled from?

sorry i missed this issue.
the key is available in tekton-chain namespace , named as signing-secret. 
we can utilize it.

**Comment by jimcadden** [comment]
> the key is available in tekton-chain namespace , named as signing-secret.
Hi @harshad16, I thought rekor would be responsible for storing the signatures. Am I mistaken?

**Comment by harshad16** [comment]
The question was about the signing secret right? like cosign key which would be used for adding the signature. 
that would be in the openshift secrets.

about the rekor, it would have the signature records.

**Comment by jimcadden** [comment]
Thanks @harshad16, I see now where I am confused. Could you quickly list the components involved and their role within the transaction, from signature creation -> verification?

**Comment by harshad16** [comment]
Surely, here is the overview:
Tekton Pipelines: pipelines that would carry out actions/tasks as building images.
Tekton chain: The controller which on the lookout for the task in pipelines, to sign the artifact with the signature using different schemas.
Cosign: schema is used to generate a signature for signing 

rekor: CLI tool to view the signed record/sort of ledger for the signatures. 
validator( kyverno or connaisseur) : the validator tool which would validate the image in the openshift cluster after being pulled

**Comment by jimcadden** [comment]
Thanks!! One more. Where is the private key, used by the tekton-chain+cosign to generate the signature, stored?

**Comment by harshad16** [comment]
It is encrypted and kept in here: https://github.com/operate-first/continuous-delivery/blob/master/tekton-chains/overlays/moc/tekton-chains-secret.enc.yaml
the argocd deploys this to operate-first openshift cluster and there it can found in the tekton chains openshift secrets.

**Comment by jimcadden** [comment]
Thanks!

**Comment by jimcadden** [comment]
@harshad16 So that so I am super clear, who has the ability to decrypt the secret (i.e., cosign key) stored in the tekton chain?

**Comment by harshad16** [comment]
very excellent question.
all the folks whose gpg key present in this file https://github.com/operate-first/continuous-delivery/blob/master/tekton-chains/overlays/moc/.sops.yaml
we are still updating it https://github.com/operate-first/continuous-delivery/issues/23
feel free to add your gpg key in there.

**Comment by lukehinds** [comment]
I would not bother using GPG, use cosign to generate ec keys, you could then just load them directly into a kube secret:

`cosign generate-key-pair k8s://tekton-chains/signing-secrets`

**Comment by harshad16** [comment]
There seems to be some misunderstanding 
the `cosign` is used to generate the keys. 
then we plan the keys in github itself via encrypting it with gpg keys of the maintainers .
the link forwarded is the list of maintainers who can decrypt the keys generated via cosign. 
@lukehinds

**Comment by lukehinds** [comment]
Do you have this design outlined anywhere that I can read?

**Comment by harshad16** [comment]
what design outline would you like?
As this was a part of tekton chain deployment in the operate-first cloud.
we use argocd to deploy apps in the operate-first cloud, for apps having secrets we use the kustomize ksops method which uses gpg encryption. Details can be found here: https://www.operate-first.cloud/apps/content/argocd-gitops/encrypting_applications.html

**Comment by lukehinds** [comment]
ack, understand. Not something to address in this issue, but we should migrate you away from GPG. It's a broken algorithm and an unwieldy tool.
