### ISSUE TITLE
Quay.io signature support

### ISSUE THREAD

**Issue by jimcadden** [AICoE/summit-2021-octo-keynote#28]
Quay.io hosted is waiting to be updated to support signatures. 

Possible work-around is to migrate pipeline to Github container registry or ttl.sh (worse case scenario)

**Comment by jimcadden** [comment]
@codificat would please you follow up with the quay team?

**Comment by codificat** [comment]
> @codificat would please you follow up with the quay team?

Yes. Current estimate is within weeks.
/assign

**Comment by codificat** [comment]
quay.io has been upgraded and now accepts signatures generated with cosign.

/close
