### ISSUE TITLE
Replace the off-the-net DonkeyCar container image

### ISSUE THREAD

**Issue by jimcadden** [AICoE/summit-2021-octo-keynote#48]
To deploy the Virtual Twin we currently use an ubuntu-based DonkeyCar container image from docker.io/<user>. We want to replace this with a fedora-based image that we own & control.

**Comment by goern** [comment]
where is the source (Dockerfile or so) that is used to build the container image?

**Comment by jimcadden** [comment]
> where is the source (Dockerfile or so) that is used to build the container image?

@goern here: https://github.com/jimcadden/donkeycar_fedora

**Comment by jimcadden** [comment]
Update base image: 
https://github.com/jimcadden/donkeycar_fedora
https://hub.docker.com/r/jcaddenibm/donkeycar_fedora
